# Write your MySQL query statement below
SELECT R.ID, SUM(R.NUM) NUM
FROM
((SELECT REQUESTER_ID ID, COUNT(*) NUM
FROM REQUESTACCEPTED
GROUP BY REQUESTER_ID)
UNION ALL
(SELECT ACCEPTER_ID ID, COUNT(*) NUM
FROM REQUESTACCEPTED
GROUP BY ACCEPTER_ID)) R
GROUP BY R.ID
ORDER BY SUM(R.NUM) DESC LIMIT 1;