# Write your MySQL query statement below
(SELECT U.NAME RESULTS
FROM MOVIERATING MR INNER JOIN USERS U
ON MR.USER_ID = U.USER_ID
GROUP BY MR.USER_ID
ORDER BY COUNT(MR.MOVIE_ID) DESC, U.NAME LIMIT 1)
UNION ALL
(SELECT M.TITLE RESULTS
FROM MOVIES M INNER JOIN MOVIERATING MR
ON M.MOVIE_ID = MR.MOVIE_ID
WHERE MR.CREATED_AT LIKE '2020-02%'
GROUP BY M.MOVIE_ID
ORDER BY AVG(MR.RATING) DESC, M.TITLE LIMIT 1);