# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID, E1.NAME, COUNT(E2.REPORTS_TO) REPORTS_COUNT, ROUND(AVG(E2.AGE)) AVERAGE_AGE
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.REPORTS_TO
GROUP BY E1.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID;