# Write your MySQL query statement below
SELECT D.NAME DEPARTMENT, E.NAME EMPLOYEE, E.SALARY
FROM (
    SELECT *, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) R
    FROM EMPLOYEE
) E INNER JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE E.R <= 3;