# Write your MySQL query statement below
SELECT DATE_FORMAT(TRANS_DATE, '%Y-%m') MONTH, COUNTRY, COUNT(*) TRANS_COUNT, SUM(IF(STATE = 'APPROVED', 1, 0)) APPROVED_COUNT, SUM(AMOUNT) TRANS_TOTAL_AMOUNT, SUM(IF(STATE = 'APPROVED', AMOUNT, 0)) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY DATE_FORMAT(TRANS_DATE, '%Y-%m'), COUNTRY;