# Write your MySQL query statement below
SELECT 'Low Salary' CATEGORY, COUNT(ACCOUNT_ID) ACCOUNTS_COUNT
FROM ACCOUNTS
WHERE INCOME < 20000
UNION
SELECT 'Average Salary' CATEGORY, COUNT(ACCOUNT_ID) ACCOUNTS_COUNT
FROM ACCOUNTS
WHERE INCOME BETWEEN 20000 AND 50000
UNION
SELECT 'High Salary' CATEGORY, COUNT(ACCOUNT_ID) ACCOUNTS_COUNT
FROM ACCOUNTS
WHERE INCOME > 50000;