# Write your MySQL query statement below
SELECT C1.VISITED_ON, SUM(C2.AMOUNT) AMOUNT, ROUND(AVG(C2.AMOUNT), 2) AVERAGE_AMOUNT
FROM (
    SELECT VISITED_ON, SUM(AMOUNT) AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON
) C1 INNER JOIN (
    SELECT VISITED_ON, SUM(AMOUNT) AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON
) C2
ON DATEDIFF(C1.VISITED_ON, C2.VISITED_ON) BETWEEN 0 AND 6
GROUP BY C1.VISITED_ON
HAVING COUNT(*) >= 7
ORDER BY C1.VISITED_ON;