# Write your MySQL query statement below
SELECT ROUND(COUNT(A2.PLAYER_ID) / COUNT(DISTINCT A1.PLAYER_ID), 2) FRACTION
FROM ACTIVITY A1 LEFT JOIN (
    SELECT PLAYER_ID, DATE_ADD(MIN(EVENT_DATE), INTERVAL 1 DAY) ED
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) A2
ON A1.PLAYER_ID = A2.PLAYER_ID AND A1.EVENT_DATE = A2.ED;