# Write your MySQL query statement below
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE SALARY < 30000 AND EMPLOYEE_ID NOT IN (
    SELECT E1.EMPLOYEE_ID
    FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID
) AND MANAGER_ID IS NOT NULL
ORDER BY EMPLOYEE_ID;