# Write your MySQL query statement below
SELECT P.PRODUCT_ID, IFNULL(ROUND(SUM(P.PRICE * US.UNITS) / SUM(US.UNITS), 2), 0) AVERAGE_PRICE
FROM PRICES P LEFT JOIN UNITSSOLD US
ON P.PRODUCT_ID = US.PRODUCT_ID AND US.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID;